name: test
run-name: ${{github.actor}} is running tests.
on:
  push:
  pull_request:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          cd listerofrepos
          go test -v
